apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: flight-booking-assistant
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "2"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/flight-booking-assistant:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "8080"
        - name: GOOGLE_CLOUD_PROJECT
          value: "ai-accelerate-devpost"
        - name: FIRESTORE_PROJECT_ID
          value: "ai-accelerate-devpost"
        volumeMounts:
        - name: service-account
          mountPath: /secrets/service-account
          readOnly: true
        - name: elastic-secrets
          mountPath: /secrets/elastic
          readOnly: true
        - name: stripe-secrets
          mountPath: /secrets/stripe
          readOnly: true
        - name: sendgrid-secrets
          mountPath: /secrets/sendgrid
          readOnly: true
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: service-account
        secret:
          secretName: service-account
      - name: elastic-secrets
        secret:
          secretName: elastic-secrets
      - name: stripe-secrets
        secret:
          secretName: stripe-secrets
      - name: sendgrid-secrets
        secret:
          secretName: sendgrid-secrets